trigger:
- '*'

pool:
  vmImage: windows-latest

container:
  image: nationalinstruments/labview:2026q1-windows-beta

steps:
- script: 'LabVIEWCLI -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Restore -Configuration "$(Build.SourcesDirectory)\packages-dev.vipc" -Headless'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Restore packages'
  retryCountOnTaskFailure: 3 # LabVIEWCLI can fail because of slow initialization

- script: 'LabVIEWCLI -AdditionalOperationDirectory "$(Build.SourcesDirectory)\Toolchain" -OperationName Test -Project "$(Build.SourcesDirectory)\LabVIEW Composition.lvproj" -ResultsFolder "$(System.DefaultWorkingDirectory)\TestResults"  -Headless'
  workingDirectory: '$(Build.SourcesDirectory)'
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
    failTaskOnFailedTests: true
